// lib/features/export_import/data/export_service.dart
import 'dart:convert';
import 'dart:io';
import 'package:path_provider/path_provider.dart';
import 'package:path/path.dart' as p;
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import '../../../../core/constants/app_constants.dart';
import '../../../member/domain/entities/person_entity.dart';
import '../../../relationship/domain/entities/relationship_entity.dart';
import '../../../tree/domain/entities/family_tree_entity.dart';

class ExportService {
  // ── JSON Export ───────────────────────────────────────────────────────────

  String exportToJson({
    required FamilyTreeEntity tree,
    required List<PersonEntity> persons,
    required List<RelationshipEntity> relationships,
  }) {
    final data = {
      'schema_version': AppConstants.jsonSchemaVersion,
      'exported_at': DateTime.now().toIso8601String(),
      'app_version': AppConstants.appVersion,
      'tree': tree.toJson(),
      'persons': persons.map((p) => p.toJson()).toList(),
      'relationships': relationships
          .where((r) =>
              r.relationshipType == RelationshipType.parentOf ||
              r.relationshipType == RelationshipType.spouseOf)
          .map((r) => r.toJson())
          .toList(),
    };
    return const JsonEncoder.withIndent('  ').convert(data);
  }

  Future<File> saveJsonToFile(String jsonContent, String treeName) async {
    final dir = await getApplicationDocumentsDirectory();
    final safeName = treeName.replaceAll(RegExp(r'[^\w\s]'), '').trim().replaceAll(' ', '_');
    final fileName =
        '${AppConstants.exportFileName}_${safeName}_${DateTime.now().millisecondsSinceEpoch}.json';
    final file = File(p.join(dir.path, fileName));
    await file.writeAsString(jsonContent);
    return file;
  }

  // ── JSON Import ───────────────────────────────────────────────────────────

  ImportData parseImportJson(String jsonContent) {
    final Map<String, dynamic> data = jsonDecode(jsonContent);

    final schemaVersion = data['schema_version'] as int? ?? 0;
    if (schemaVersion > AppConstants.jsonSchemaVersion) {
      throw FormatException(
          'This backup was created with a newer version of the app. '
          'Please update the app to import it.');
    }

    final treeJson = data['tree'] as Map<String, dynamic>;
    final tree = FamilyTreeEntity.fromJson(treeJson);

    final personsJson = data['persons'] as List<dynamic>? ?? [];
    final persons = personsJson
        .map((j) => PersonEntity.fromJson(j as Map<String, dynamic>))
        .toList();

    final relsJson = data['relationships'] as List<dynamic>? ?? [];
    final relationships = relsJson
        .map((j) =>
            RelationshipEntity.fromJson(j as Map<String, dynamic>))
        .toList();

    return ImportData(
      tree: tree,
      persons: persons,
      relationships: relationships,
    );
  }

  // ── PDF Export ────────────────────────────────────────────────────────────

  Future<File> exportToPdf({
    required FamilyTreeEntity tree,
    required List<PersonEntity> persons,
  }) async {
    final pdf = pw.Document();
    final sortedPersons = [...persons]
      ..sort((a, b) => (a.birthYear ?? 0).compareTo(b.birthYear ?? 0));

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(40),
        header: (context) => pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Text(
              tree.name,
              style: pw.TextStyle(
                fontSize: 24,
                fontWeight: pw.FontWeight.bold,
              ),
            ),
            if (tree.description != null)
              pw.Text(
                tree.description!,
                style: const pw.TextStyle(fontSize: 12, color: PdfColors.grey700),
              ),
            pw.Divider(color: PdfColors.grey400),
            pw.SizedBox(height: 8),
          ],
        ),
        footer: (context) => pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Text(
              'Generated by Family Tree App • ${DateTime.now().year}',
              style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey),
            ),
            pw.Text(
              'Page ${context.pageNumber} of ${context.pagesCount}',
              style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey),
            ),
          ],
        ),
        build: (context) => [
          pw.Text(
            '${persons.length} Family Members',
            style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold, color: PdfColors.grey700),
          ),
          pw.SizedBox(height: 16),
          ...sortedPersons.map((person) => _buildPersonBlock(person)),
        ],
      ),
    );

    final dir = await getApplicationDocumentsDirectory();
    final safeName = tree.name.replaceAll(RegExp(r'[^\w\s]'), '').trim().replaceAll(' ', '_');
    final fileName = '${AppConstants.exportFileName}_${safeName}.pdf';
    final file = File(p.join(dir.path, fileName));
    await file.writeAsBytes(await pdf.save());
    return file;
  }

  pw.Widget _buildPersonBlock(PersonEntity person) {
    return pw.Container(
      margin: const pw.EdgeInsets.only(bottom: 12),
      padding: const pw.EdgeInsets.all(12),
      decoration: pw.BoxDecoration(
        border: pw.Border.all(color: PdfColors.grey300),
        borderRadius: const pw.BorderRadius.all(pw.Radius.circular(6)),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Text(
                person.fullName,
                style: pw.TextStyle(
                  fontSize: 14,
                  fontWeight: pw.FontWeight.bold,
                ),
              ),
              pw.Text(
                person.isLiving ? 'Living' : 'Deceased',
                style: pw.TextStyle(
                  fontSize: 10,
                  color: person.isLiving ? PdfColors.green700 : PdfColors.grey600,
                ),
              ),
            ],
          ),
          pw.SizedBox(height: 4),
          pw.Text(
            person.lifespan,
            style: const pw.TextStyle(fontSize: 11, color: PdfColors.grey700),
          ),
          if (person.birthPlace != null)
            pw.Text('Born: ${person.birthPlace}',
                style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey600)),
          if (person.occupation != null)
            pw.Text('Occupation: ${person.occupation}',
                style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey600)),
          if (person.biography != null && person.biography!.isNotEmpty)
            pw.Padding(
              padding: const pw.EdgeInsets.only(top: 6),
              child: pw.Text(
                person.biography!.length > 300
                    ? '${person.biography!.substring(0, 300)}…'
                    : person.biography!,
                style: const pw.TextStyle(fontSize: 10),
              ),
            ),
        ],
      ),
    );
  }
}

// ─── Import Data Holder ───────────────────────────────────────────────────────

class ImportData {
  final FamilyTreeEntity tree;
  final List<PersonEntity> persons;
  final List<RelationshipEntity> relationships;

  const ImportData({
    required this.tree,
    required this.persons,
    required this.relationships,
  });
}
